### ISSUE TITLE
Experiential use and license

### ISSUE THREAD

**Issue by batinium** [bfeber/FPS#2]
Hello!

I've just found about this repo through your YouTube channel. I'm a student studying computer science and I'd like to experiment with this repo and possibly build a pet project, though I'm not sure what I want to exactly do. Before I start working on it I wanted to get your permission to do so, if I do something with it, I'll certainly give you the credit.
Can I work on this and possibly create a pet project for my portfolio?

Cheers!

**Comment by gb2dev** [comment]
Sure, do what you want with it. But keep in mind that as a placeholder it currently has assets from Half-Life 2 in it (sounds, weapon models, textures). You should probably replace those with original ones (I should do that as well, but I've been busy with other projects).
