### ISSUE TITLE
Where can I find the weapons textures used in this video ?  

### ISSUE THREAD

**Issue by kenkaniffer** [bfeber/FPS#3]
Hi, just wondering if theres a way to get the textures for the weapons and other objects that are shown in this video
https://www.youtube.com/watch?v=eNKqYttPNO8

Thanks in advance

**Comment by kenkaniffer** [comment]
It seems that the textures wont load if launched in the newest version of godot 4

**Comment by gb2dev** [comment]
They're just the Half-Life 2 textures and models ripped from the game. I'll have to replace them anyways in the future for copyright reasons obviously
